Add "exe" and "shared" modes to nr-make cli

diff --git a/nr-make b/nr-make
--- a/nr-make
+++ b/nr-make
@@ -2,14 +2,25 @@
 # ===============================================================
 # This is a make file generator for the nr-make system.
 # ===============================================================
-echo "nr-make: project generator"
 
 # ===============================================================
 # Utility functions
 # ===============================================================
 error() {
-    echo -e >&2 "$@"
+    echo -e >&2 "error: $@"
     exit 1
+}
+
+check() {
+    local code=$?
+    (( code > 0 )) && error "$@"
+    return 0
+}
+
+assert_non_empty() {
+    local __var="$1"; local __val
+    eval "__val=\$${__var}"
+    [[ "$__val" ]]; check "$__var is empty"
 }
 
 log() { echo -e "[LOG] $@"; }
@@ -59,7 +70,7 @@ makefile_link() {
 }
 
 # ===============================================================
-# The empty program that will be created
+# Some Stub Source Files
 # ===============================================================
 stub_main='// Generated by nr-make
 
@@ -71,6 +82,16 @@ int main()
 {
     cout << "Hello, World!" << endl;
     return 0;
+}'
+
+stub_so='// Generated by nr-make
+
+#include <iostream>
+
+using namespace std;
+
+void hello() {
+    cout << "Hello, World!" << endl;
 }'
 
 # ===============================================================
@@ -113,7 +134,53 @@ init() {
     return 1
 }
 
+# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
+#                        Make Shared Object
+# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
+stub_makefile='ifndef root
+    include $(dir $(lastword $(MAKEFILE_LIST)))../Makefile
+else
+    # Must enter in order of dependencies.
+    locations := # Put any additional sublocations here
+    $(call enter_all,$(locations))
+
+    $(call MAKE_WHAT,NAME,NAME)
+endif'
+
+new_module() {
+    local what="$1"
+    local stub="$2"
+    local name="$3"
+    local folder="$4"
+    assert_non_empty what
+    assert_non_empty stub
+    assert_non_empty name
+    assert_non_empty folder
+    [[ ! -e "$folder/Makefile" ]]
+    check "$folder/Makefile already exists"
+    mkdir -p "$folder"
+    check "failed to create folder $folder"
+    body="$stub_makefile"
+    body="${body//NAME/$name}"
+    body="${body//MAKE_WHAT/$what}"
+    echo "$body" >"$folder/Makefile"
+    check "failed to write $folder/Makefile"
+    echo "$stub" >"$folder/$name.cpp"
+    check "failed to write $folder/$name.cpp"
+    # Give the user a list of files we've created.
+    echo 'Created:'
+    find "$folder"
+}
+
+exe()    { new_module make_exe "$stub_main" "$@"; }
+shared() { new_module make_so  "$stub_so"   "$@"; }
+
+# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
+#                              Usage
+# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 usage='
+nr-make: project generator
+
 Usage: nr-make mode [...]
 
     mode can be: init
@@ -128,6 +195,16 @@ Example 2. to create a new simple project
            created if it does not exist):
 
     $ nr-make init simple path/to/folder
+
+Example 3. to create a shared library in a
+           source folder:
+
+    $ nr-make shared name path/to/folder
+
+Example 4. to create an executable in a
+           source folder:
+
+    $ nr-make exe name path/to/folder
 '
 
 # ===============================================================
@@ -137,17 +214,17 @@ main() {
     mode="$1"; shift
 
     case "$mode" in
-        init)
-            init "$@"
-            return $?
-        ;;
+        init)   ;;
+        exe)    ;;
+        shared) ;;
         *)
             echo "$usage"
             return 1
         ;;
     esac
-    # !! Should not get here
-    return 1
+
+    # The mode is recognized, so run it.
+    $mode "$@"
 }
 
 # ===============================================================
